# Generated by Django 5.2.5 on 2025-11-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedidoImagen',
            new_name='PedidoImagenes',
        ),
    ]
