# Generated by Django 5.2.5 on 2025-12-01 04:18

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_rename_pedidoimagen_pedidoimagenes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_requerida',
            new_name='fecha_necesidad',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='cliente',
            new_name='nombre_cliente',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='creado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_creado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pedido',
            name='imagen_referencia',
            field=models.ImageField(blank=True, null=True, upload_to='pedidos/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='Solicitado', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='plataforma',
            field=models.CharField(default='Página Web', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
