# Generated by Django 5.2.5 on 2025-12-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_fecha_requerida_pedido_fecha_necesidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('proceso', 'En proceso'), ('realizada', 'Realizada'), ('entregada', 'Entregada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='solicitado', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='plataforma',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('presencial', 'Presencial'), ('web', 'Sitio Web'), ('otro', 'Otro')], default='web', max_length=20),
        ),
    ]
